// Pins the native Android Rive runtime that `rive-react-native` pulls in.
// 9.13.0+ causes scroll jank on Android release builds (see companion task
// notes) — force 9.12.2 regardless of what the library's own POM resolves to.
// `android/` is generated by `expo prebuild` (gitignored), so the pin has to
// live in a config plugin, not a hand-edit of build.gradle, or it's lost on
// the next prebuild.
const { withAppBuildGradle } = require('@expo/config-plugins');

const PINNED_VERSION = '9.12.2';
const MARKER = '// withRiveAndroidVersion';

function withRiveAndroidVersion(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(MARKER)) {
      return mod;
    }

    const block = `
${MARKER}
configurations.all {
    resolutionStrategy {
        force "app.rive:rive-android:${PINNED_VERSION}"
    }
}
`;

    mod.modResults.contents += block;
    return mod;
  });
}

module.exports = withRiveAndroidVersion;
