// This machine's installed NDK 27.1.12297006 is missing `source.properties`
// (corrupt/incomplete SDK component install), which fails every Android
// build with CXX1101. NDK 27.0.12077973 is also installed and complete —
// pin to it. `expo-build-properties` (57.0.20, current SDK 57) has no
// `android.ndkVersion` option, so this has to be a small plugin of its own.
// `android/` is generated by `expo prebuild` (gitignored), so this MUST be a
// config plugin, not a hand-edit of build.gradle — a hand-edit is silently
// lost on the next `expo prebuild --clean` (this bit us once already).
const { withProjectBuildGradle } = require('@expo/config-plugins');

const NDK_VERSION = '27.0.12077973';
const MARKER = '// withNdkVersion';

// Must land BEFORE `apply plugin: "com.facebook.react.rootproject"` — that
// plugin reads `rootProject.ext.ndkVersion` synchronously as it applies, so
// setting `ext` after it (e.g. appended at file end) is too late and gets
// silently ignored in favor of the plugin's own default.
const APPLY_ANCHOR = 'apply plugin: "expo-root-project"';

function withNdkVersion(config) {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(MARKER)) {
      return mod;
    }

    const block = `${MARKER}
ext {
    ndkVersion = "${NDK_VERSION}"
}

`;

    if (mod.modResults.contents.includes(APPLY_ANCHOR)) {
      mod.modResults.contents = mod.modResults.contents.replace(APPLY_ANCHOR, `${block}${APPLY_ANCHOR}`);
    } else {
      // Anchor not found (template changed) — falling back to appending is
      // still correct in the common case where nothing else sets `ext.ndkVersion`.
      mod.modResults.contents += `\n${block}`;
    }
    return mod;
  });
}

module.exports = withNdkVersion;
